backend/urls.py
from django.urls import path
from . import views
from . import export_function
from . import pdf_generator_func 

app_name = 'backend' 

urlpatterns = [
    path('', views.backend_dashboard, name='backend_dashboard'),
    path('login/', views.backend_login, name='backend_login'),
    path('logout/', views.backend_logout, name='backend_logout'),

    # User Mannagement
    path('user/', views.UserListView.as_view(), name='user_list'),
    path('user/add/', views.user_add, name='user_add'),
    path('user/update/<str:data_id>/', views.user_update, name='user_update'),
    path('user/password/reset/<str:data_id>/', views.reset_password, name='reset_password'),
    path('user/permission/<int:user_id>/', views.user_permission, name='user_permission'),

    # Inventory Management
    path('inventory/', views.inventory_dashboard, name='inventory_dashboard'),

    # Setting
    path('settings/', views.setting_dashboard, name='setting_dashboard'),
    path('website-setting/', views.website_setting, name='website_setting'),
    path('email-configuration/', views.EmailConfigurationCreateUpdateView.as_view(), name='email_configuration'),
    path('sms-configuration/', views.SMSConfigurationCreateUpdateView.as_view(), name='sms_configuration'),

    # path('cities/', views.cities, name='cities'),
    # path('company-setting/', views.company_setting, name='company_setting'),
    # path('add-new-company/', views.add_new_company, name='add_new_company'),

    # Product brand
    path('brand/', views.BrandListView.as_view(), name='brand_list'),
    path('brand-details/<int:pk>/', views.brand_detail_view, name='brand_details_view'),
    path('add-brand/', views.BrandCreateView.as_view(), name='add_brand'),
    path('brand-update/<int:pk>/', views.BrandUpdateView.as_view(), name='brand_update'),
    path('brand-delete/<int:pk>/', views.brand_delete_view, name='brand_delete'),


    # Product main category URLs
    path('category/', views.MainCategoryListView.as_view(), name='category_list'),
    path('category-details/<int:pk>/', views.category_detail_view, name='category_detail_view'),
    path('add-category/', views.CategoryCreateView.as_view(), name='add_category'),
    path('category-update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', views.category_delete_view, name='product_main_category_delete'),
    path('upload-category-excel/', views.upload_category_excel, name='upload_category_excel'), 

    # Product sub category URLs
    path('sub-category/', views.SubCategoryListView.as_view(), name='sub_category_list'),
    path('sub-category-detail/<int:pk>/', views.sub_category_details_view, name='sub_category_details_view'),
    path('add-sub-category/', views.SubCategoryCreateView.as_view(), name='add_sub_category'),
    path('sub-category-update/<int:pk>/', views.SubCategoryUpdateView.as_view(), name='sub_category_update'),
    path('sub-category-delete/<int:pk>/', views.sub_category_delete_view, name='sub_category_delete'),
    path('upload-sub-category-excel/', views.upload_sub_category_excel, name='upload_sub_category_excel'),

    # # Product child category URLs
    path('child-category/', views.ChildCategoryListView.as_view(), name='child_category_list'),
    path('child-category-detail/<int:pk>/', views.child_category_details_view, name='child_category_details_view'),
    path('add-child-category/', views.ChildCategoryCreateView.as_view(), name='add_child_category'),
    path('child-category-update/<int:pk>/', views.ChildCategoryUpdateView.as_view(), name='child_category_update'),
    path('child-category-delete/<int:pk>/', views.child_category_delete_view, name='child_category_delete'),
    path('upload-child-category-excel/', views.upload_child_category_excel, name='upload_child_category_excel'), 

    # Attribute list URLs
    path('attributes/', views.AttributeListView.as_view(), name='attribute_list'),
    path('attribute-details/<int:pk>/', views.attribute_details_view, name='attribute_details'),
    path('add-attribute/', views.AttributeCreateView.as_view(), name='add_attribute_list'),
    path('attribute-list-update/<int:pk>/', views.AttributeUpdateView.as_view(), name='attribute_list_update'),
    path('attribute-list-delete/<int:pk>/', views.attribute_delete_view, name='attribute_list_delete'),

    # Attribute value list URLs
    path('attribute-value-list/', views.AttributeValueListView.as_view(), name='value_list'),
    path('attribute-value-details/<int:pk>/', views.value_details_view, name='value_details'),
    path('add-attribute-value/', views.AttributeValueCreateView.as_view(), name='add_value_list'),
    path('attribute-value-update/<int:pk>/', views.AttributeValueUpdateView.as_view(), name='value_update'),
    path('attribute-value-delete/<int:pk>/', views.value_delete_view, name='value_delete'),

    # Product list URLs
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product-details/<int:pk>/', views.product_details_view, name='product_details'),
    path('add-product/', views.ProductCreateView.as_view(), name='add_product'),
    path('product-update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', views.product_delete_view, name='product_delete'),
    path('download-product-excel/', export_function.export_products_to_excel, name='export_products_to_excel'),
    path('upload-product-excel/', views.upload_product_excel, name='upload_product_excel'),
    path('download-product-pdf/', pdf_generator_func.generate_pdf_from_template, name='export_products_to_pdf'), 

    # Product attribute URLs
    path('product-attribute-list/', views.ProductAttibuteListView.as_view(), name='product_attribute_list'),
    path('product-attribute-details/<int:pk>/', views.product_attribute_details_view, name='product_attribute_details'),
    path('add-product-attribute/', views.ProductAttributeCreateView.as_view(), name='add_product_attribute'),
    path('product-attribute-update/<int:pk>/', views.ProductAttributeUpdateView.as_view(), name='product_attribute_update'),
    path('product-attribute-delete/<int:pk>/', views.product_attribute_delete_view, name='product_attribute_delete'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

from auditlog.registry import auditlog


class AdminUser(models.Model):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='admin')
    phone = models.CharField(max_length=20, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    profile_image = models.ImageField(upload_to='admin_profile_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'admin_user'

    def get_name(self):
        first_name = self.user.first_name.strip() if self.user.first_name else ""
        last_name = self.user.last_name.strip() if self.user.last_name else ""
        return f"{first_name} {last_name}".strip() if first_name or last_name else self.user.username

    def get_profile_photo_url(self):
        if self.profile_image:
            return self.profile_image.url
        return f"https://ui-avatars.com/api/?name={self.get_name()}&background=random"

    def __str__(self):
        return self.get_name() if self.user else ""


class LoginLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    wrong_password = models.CharField(max_length=100, blank=True, null=True)
    login_ip = models.CharField(max_length=100, blank=True, null=True)
    login_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "login_logs"

    def __str__(self) -> str:
        return self.username


class BackendMenu(models.Model):
    module_name = models.CharField(max_length=100, db_index=True)
    menu_name = models.CharField(max_length=100, unique=True, db_index=True)
    menu_url = models.CharField(max_length=250, unique=True)
    menu_icon = models.CharField(max_length=250, blank=True, null=True)
    parent_id = models.IntegerField()
    is_main_menu = models.BooleanField(default=False)
    is_sub_menu = models.BooleanField(default=False)
    is_sub_child_menu = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "backend_menu"

    def __str__(self) -> str:
        return self.menu_name


class UserMenuPermission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_permission")
    menu = models.ForeignKey(BackendMenu, on_delete=models.CASCADE, related_name="user_permission")
    can_view = models.BooleanField(default=False)
    can_add = models.BooleanField(default=False)
    can_update = models.BooleanField(default=False)
    can_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by_user_permission")
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="updated_by_user_permission", blank=True, null=True)
    deleted_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="deleted_by_user_permission", blank=True, null=True)
    is_active = models.BooleanField(default=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        db_table = "user_permission"

    def __str__(self):
        return str(self.menu)


# Frontend Settings
class FrontendSettings(models.Model):
    site_title = models.CharField(max_length=255, default="My Website")
    logo = models.ImageField(upload_to='settings/logo/', blank=True, null=True)
    favicon = models.ImageField(upload_to='settings/favicon/', blank=True, null=True)

    contact_email = models.EmailField(blank=True, null=True)
    contact_phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)

    facebook_url = models.URLField(blank=True, null=True)
    instagram_url = models.URLField(blank=True, null=True)

    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='frontend_settings_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='frontend_settings_updated_by', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'frontend_settings'
        verbose_name_plural = 'Frontend Settings'
        ordering = ['-is_active']

    def __str__(self):
        return self.site_title if self.site_title else "Frontend Settings"
    

class FrontendDesignSettings(models.Model):
    header_choices = (('header1', 'Header 1'), ('header2', 'Header 2'), ('header3', 'Header 3'))
    footer_choices = (('footer1', 'Footer 1'), ('footer2', 'Footer 2'), ('footer3', 'Footer 3'))
    font_choices = (('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Times New Roman', 'Times New Roman'))

    header = models.CharField(max_length=10, choices=header_choices, default='header1')
    footer = models.CharField(max_length=10, choices=footer_choices, default='footer1')
    primary_color = models.CharField(max_length=20, default="#000000")
    secondary_color = models.CharField(max_length=20, default="#FFFFFF")
    font_family = models.CharField(max_length=50, choices=font_choices, default='arial')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='design_settings_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='design_settings_updated_by', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False, blank=True, null=True)

    class Meta:
        db_table = 'frontend_design_settings'
        verbose_name_plural = 'Frontend Design Settings'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.header} - {self.footer} - {self.font_family}"


class EmailConfiguration(models.Model):
    email_host = models.CharField(max_length=255)
    email_port = models.IntegerField()
    email_host_user = models.EmailField()
    email_host_password = models.CharField(max_length=255)
    use_tls = models.BooleanField(default=True)
    use_ssl = models.BooleanField(default=False)
    email_from_name = models.CharField(max_length=255, default="")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_config_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_config_updated_by', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'email_configuration'

    def __str__(self):
        return self.email_host_user


class SMSConfiguration(models.Model):
    sms_provider_choices = (('ssl', 'SSL'),)
    sms_configuration_type_choices = (('api_token', 'API Token'), ('password', 'Password'),)

    sms_provider = models.CharField(max_length=50, choices=sms_provider_choices, default='ssl', db_index=True)
    sms_configuration_type = models.CharField(max_length=100, choices=sms_configuration_type_choices, default='api_token', db_index=True)
    api_url = models.URLField(max_length=255, blank=True, null=True)
    sms_id = models.CharField(max_length=100, blank=True, null=True)
    api_token = models.TextField(blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sms_config_created_by_user")
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sms_config_updated_by_user", blank=True, null=True)
    deleted_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sms_config_deleted_by_user", blank=True, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        db_table = "sms_configurations"

    def __str__(self):
        return f"{self.get_sms_provider_display()} - {self.get_sms_configuration_type_display()} ({self.sms_id})"


class SMSLog(models.Model):
    mobile_number = models.CharField(max_length=15, db_index=True)
    message_text = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=15, blank=True, null=True)
    ip_address = models.CharField(max_length=50, blank=True, null=True)
    sms_configuration = models.ForeignKey(SMSConfiguration, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="sms_sent_created_by_user",
        blank=True, null=True
    )
    deleted = models.BooleanField(default=False)

    class Meta:
        db_table = "sms_log"

    def __str__(self):
        return str(self.mobile_number)
# Frontend Settings


# Inventory
class ProductBrand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    image = models.ImageField(upload_to='inventory/brand_images/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

backend/templates/product/maincategories/add_category.html
{% extends 'base.html' %}

{% block title %} Category {% endblock %}

{% block content %}
    <section class="customer-list-section">
        <div class="container">
            <div class="content">

                <div class="title-box">
                    <div class="page-title">
                        <h3>Add New  Main Category</h3>
                    </div>
                    <div class="breadcrumbs">
                        <ul class="breadcrumbs-list">
                            <li><a href="/"><span><img src="/static/images/icons/Home.svg" alt="more"></span>Home</a></li>
                            <li><a href="{% url 'backend:category_list' %}">Category List</a></li>
                            <li><a href="#">Add New Category</a></li>
                        </ul>
                    </div>
                    
                </div>

                <div class="form-area-content">
                    <div class="form-inner-content">
                        
                        <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- Display messages if any -->
                        {% if messages %}
                        <div class="alert alert-info" role="alert" style="color: red">
                            {% for message in messages %}
                            <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="input-field">
                                <label for="id_name">Category Name</label>
                                {{ form.name }}
                            </div>
                            <div class="input-field">
                                <label for="id_ordering">Ordering</label>
                                {{ form.ordering }}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-field-full">
                                <label for="id_description">Description</label>
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-field input-photo">
                                <label for="id_image">Image</label>
                                {% if form.instance.image %}
                                <div class="current-image mb-2">
                                    <p>Current: <a href="{{ form.instance.image.url }}" target="_blank">{{ form.instance.image.name }}</a></p>
                                </div>
                                {% endif %}
                                {{ form.image }}
                            </div>
                            
                        </div>

                        <div class="form-group">
                            <div class="form-button">
                                <button type="submit" class="button blue-button">Save</button>
                                <a href="{% url 'backend:category_list' %}" class="button primary-button cancle-button">Cancel</a>
                            </div>
                        </div>
                    </form>
                    
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

{% block extra_js %}
<script>
$(document).ready(function() {
    $('.select2-single').select2();
});
</script>
{% endblock %}

backend/templates/product/maincategories/main_cat_list.html
{% extends 'base.html' %}

{% block title %}Main Category List | Ecommerce{% endblock %}

{% block content %}
<section class="customer-list-section">
    <div class="container">
        <div class="content">
            <div class="title-box">
                <div class="page-title">
                    <h3>Main Category List</h3>
                </div>
                <div class="breadcrumbs">
                    <ul class="breadcrumbs-list">
                        <li><a href="/backend/dashboard/"><span><img src="/static/images/icons/Home.svg" alt="home" /></span>Home</a></li>
                        <li><a href="#">Main Category List</a></li>
                    </ul>
                </div>

                <div class="top-button">
                    <div class="button-box d-flex align-items-center gap-2">

                        <div class="dropdown">
                            <button class=" dropdown-toggle" type="button" id="actionDropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
                                Actions
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="actionDropdownMenu">
                                <li><a class="dropdown-item" href="?{{ query_params }}&export=excel" target="_blank">Export Excel</a></li>
                                <li><a class="dropdown-item" href="{% url 'backend:upload_category_excel' %}" target="_blank">Import Excel</a></li>
                                <li><a class="dropdown-item" href="?{{ params }}&export=pdf" target="_blank">Export PDF</a></li>
                            </ul>
                        </div>

                        <!-- Add New Button -->
                        <a class="button primary-button d-flex align-items-center gap-1" href="{% url 'backend:add_category' %}">
                            <img src="/static/images/icons/add.svg" alt="Add" />
                            Add New
                        </a>

                    </div>
                </div>
 
           {% comment %} 
            <div class="top-button">
                    <div class="button-box">
                        <a class="button primary-button" href="{% url 'backend:add_category' %}">
                            <span><img src="/static/images/icons/add.svg" alt="add" /></span>Add New
                        </a>
                    </div>
                </div>  
            </div> 
            {% endcomment %}

            <form method="get" id="filterForm" class="mb-3 d-flex align-items-center flex-wrap" style="gap: 10px;">

                            <select name="name" class="form-control select2-items" style="width: 180px;">
                                <option value="">All Categories</option>
                                {% for cat in filter_data.category_name %}
                                    <option value="{{ cat.id }}" {% if request.GET.name == cat.id|stringformat:"s" %}selected{% endif %}>
                                        {{ cat.name }}
                                    </option>
                                {% endfor %}
                            </select>



                            <input type="date" name="created_from" class="form-control" placeholder="Created From" value="{{ filter_created_from }}" style="width: 180px;">
                            <input type="date" name="created_to" class="form-control" placeholder="Created To" value="{{ filter_created_to }}" style="width: 180px;"> 

                            <button type="submit" class="btn btn-primary">Filter</button>
                            <a href="{% url 'backend:category_list' %}" class="btn btn-danger">Reset</a>

            </form>

            <div class="listing-box">
                <div class="table table-border-bottom">

                    {% if messages %}
                        <div class="alert alert-info" role="alert" style="color: green">
                            {% for message in messages %}
                            <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <table>
                        <thead>
                            <tr>
                                <th class="text-center">SL No.</th>
                                <th class="text-left">Name</th>
                                <th class="text-left">Description</th>
                                <th class="text-left">Created By</th>
                                <th class="text-center">Status</th>
                                <th class="text-left">Created Date</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in product_main_categories %}
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-left"><a href="{% url 'backend:category_detail_view' data.id %}">{{ data.name }}</a></td>
                                <td class="text-left">{{ data.description|truncatewords:10 }}</td>
                                <td class="text-left">{{ data.created_by }}</td>
                                <td class="text-center">
                                    {% if data.is_active %}
                                        <span class="active"><img src="/static/images/icons/ellipse-active.svg" alt="yes" /></span>Yes
                                    {% else %}
                                        <span class="inactive"><img src="/static/images/icons/ellipse-inactive.svg" alt="no" /></span>No
                                    {% endif %}
                                </td>
                                <td class="text-left">{{ data.created_at|date:"d-M-Y" }}</td>
                                <td class="text-center">
                                    <span class="more"><a href="{% url 'backend:category_detail_view' data.id %}"><i class="fas fa-eye font-weight500"></i></a></span>
                                    <span class="more"><a href="{% url 'backend:category_update' data.id %}"><i class="fas fa-edit font-weight500"></i></a></span>
                                    <span class="more">
                                        <form method="post" action="{% url 'backend:product_main_category_delete' data.id %}" style="display: inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="" onclick="return confirm('Are you sure you want to delete this category?');">
                                                <i class="fas fa-trash-alt font-weight500"></i>
                                            </button>
                                        </form>
                                    </span>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="7" class="text-center">No Data found.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- pagination -->
                <div class="pagination">
                    {% if last_page_number > 1 %}
                    <nav aria-label="navigation">
                        <ul class="pagination justify-content-center">
                            {% if product_main_categories.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ product_main_categories.previous_page_number }}{% if params %}&{{ params }}{% endif %}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            {% endif %}
                            {% for i in paginator_list %}
                            <li class="page-item {% if product_main_categories.number == i %}active{% endif %}">
                                <a class="page-link" href="?page={{ i }}{% if params %}&{{ params }}{% endif %}">{{ i }}</a>
                            </li>
                            {% endfor %}
                            {% if product_main_categories.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ product_main_categories.next_page_number }}{% if params %}&{{ params }}{% endif %}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


{% block extra_js %}
    <script>
        $(document).ready(function() {
            $('.select2-items').select2();
        });

        document.getElementById('filterForm').addEventListener('submit', function (e) {
            const inputs = this.querySelectorAll('input, select');
            for (let i = 0; i < inputs.length; i++) {
                if (!inputs[i].value) {
                    inputs[i].disabled = true;
                }
            }
        });
    </script>
{% endblock %}