backend/urls.py
from django.urls import path
from . import views
from . import export_function
from . import pdf_generator_func 

app_name = 'backend' 

urlpatterns = [
    path('', views.backend_dashboard, name='backend_dashboard'),
    path('login/', views.backend_login, name='backend_login'),
    path('logout/', views.backend_logout, name='backend_logout'),

    # User Mannagement
    path('user/', views.UserListView.as_view(), name='user_list'),
    path('user/add/', views.user_add, name='user_add'),
    path('user/update/<str:data_id>/', views.user_update, name='user_update'),
    path('user/password/reset/<str:data_id>/', views.reset_password, name='reset_password'),
    path('user/permission/<int:user_id>/', views.user_permission, name='user_permission'),

    # Inventory Management
    path('inventory/', views.inventory_dashboard, name='inventory_dashboard'),

    # Setting
    path('settings/', views.setting_dashboard, name='setting_dashboard'),
    path('website-setting/', views.website_setting, name='website_setting'),
    path('email-configuration/', views.EmailConfigurationCreateUpdateView.as_view(), name='email_configuration'),
    path('sms-configuration/', views.SMSConfigurationCreateUpdateView.as_view(), name='sms_configuration'),

    # path('cities/', views.cities, name='cities'),
    # path('company-setting/', views.company_setting, name='company_setting'),
    # path('add-new-company/', views.add_new_company, name='add_new_company'),

    # Product brand
    path('brand/', views.BrandListView.as_view(), name='brand_list'),
    path('brand-details/<int:pk>/', views.brand_detail_view, name='brand_details_view'),
    path('add-brand/', views.BrandCreateView.as_view(), name='add_brand'),
    path('brand-update/<int:pk>/', views.BrandUpdateView.as_view(), name='brand_update'),
    path('brand-delete/<int:pk>/', views.brand_delete_view, name='brand_delete'),


    # Product main category URLs
    path('category/', views.MainCategoryListView.as_view(), name='category_list'),
    path('category-details/<int:pk>/', views.category_detail_view, name='category_detail_view'),
    path('add-category/', views.CategoryCreateView.as_view(), name='add_category'),
    path('category-update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', views.category_delete_view, name='product_main_category_delete'),
    path('upload-category-excel/', views.upload_category_excel, name='upload_category_excel'), 

    # Product sub category URLs
    path('sub-category/', views.SubCategoryListView.as_view(), name='sub_category_list'),
    path('sub-category-detail/<int:pk>/', views.sub_category_details_view, name='sub_category_details_view'),
    path('add-sub-category/', views.SubCategoryCreateView.as_view(), name='add_sub_category'),
    path('sub-category-update/<int:pk>/', views.SubCategoryUpdateView.as_view(), name='sub_category_update'),
    path('sub-category-delete/<int:pk>/', views.sub_category_delete_view, name='sub_category_delete'),
    path('upload-sub-category-excel/', views.upload_sub_category_excel, name='upload_sub_category_excel'),

    # # Product child category URLs
    path('child-category/', views.ChildCategoryListView.as_view(), name='child_category_list'),
    path('child-category-detail/<int:pk>/', views.child_category_details_view, name='child_category_details_view'),
    path('add-child-category/', views.ChildCategoryCreateView.as_view(), name='add_child_category'),
    path('child-category-update/<int:pk>/', views.ChildCategoryUpdateView.as_view(), name='child_category_update'),
    path('child-category-delete/<int:pk>/', views.child_category_delete_view, name='child_category_delete'),
    path('upload-child-category-excel/', views.upload_child_category_excel, name='upload_child_category_excel'), 

    # Attribute list URLs
    path('attributes/', views.AttributeListView.as_view(), name='attribute_list'),
    path('attribute-details/<int:pk>/', views.attribute_details_view, name='attribute_details'),
    path('add-attribute/', views.AttributeCreateView.as_view(), name='add_attribute_list'),
    path('attribute-list-update/<int:pk>/', views.AttributeUpdateView.as_view(), name='attribute_list_update'),
    path('attribute-list-delete/<int:pk>/', views.attribute_delete_view, name='attribute_list_delete'),

    # Attribute value list URLs
    path('attribute-value-list/', views.AttributeValueListView.as_view(), name='value_list'),
    path('attribute-value-details/<int:pk>/', views.value_details_view, name='value_details'),
    path('add-attribute-value/', views.AttributeValueCreateView.as_view(), name='add_value_list'),
    path('attribute-value-update/<int:pk>/', views.AttributeValueUpdateView.as_view(), name='value_update'),
    path('attribute-value-delete/<int:pk>/', views.value_delete_view, name='value_delete'),

    # Product list URLs
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product-details/<int:pk>/', views.product_details_view, name='product_details'),
    path('add-product/', views.ProductCreateView.as_view(), name='add_product'),
    path('product-update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', views.product_delete_view, name='product_delete'),
    path('download-product-excel/', export_function.export_products_to_excel, name='export_products_to_excel'),
    path('upload-product-excel/', views.upload_product_excel, name='upload_product_excel'),
    path('download-product-pdf/', pdf_generator_func.generate_pdf_from_template, name='export_products_to_pdf'), 

    # Product attribute URLs
    path('product-attribute-list/', views.ProductAttibuteListView.as_view(), name='product_attribute_list'),
    path('product-attribute-details/<int:pk>/', views.product_attribute_details_view, name='product_attribute_details'),
    path('add-product-attribute/', views.ProductAttributeCreateView.as_view(), name='add_product_attribute'),
    path('product-attribute-update/<int:pk>/', views.ProductAttributeUpdateView.as_view(), name='product_attribute_update'),
    path('product-attribute-delete/<int:pk>/', views.product_attribute_delete_view, name='product_attribute_delete'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/views.py
import os 
import pandas as pd 
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from django.utils import timezone 

from datetime import datetime
from urllib.parse import urlencode

from backend.common_func import checkUserPermission
from backend.decorators import admin_required
from backend.models import (
    LoginLog, AdminUser, BackendMenu, UserMenuPermission, FrontendSettings, EmailConfiguration, SMSLog, SMSConfiguration, ProductBrand,
    ProductMainCategory, ProductSubCategory, ProductChildCategory, AttributeList, AttributeValueList, ProductList, ProductAttribute,
    FrontendDesignSettings,
)
from backend.forms import (
    CustomUserLoginForm, UserCreateForm, FrontendSettingsForm, EmailConfigurationForm, SMSConfigurationForm, ProductBrandForm,
    ProductMainCategoryForm, ProductSubCategoryForm, ProductChildCategoryForm, AttributeListForm, AttributeValueListForm,
    ProductListForm, ProductAttributeForm, FrontendDesignSettingsForm
)

from backend.export_excel import export_data_to_excel 
from backend.get_fks_key_instance import get_foreign_key_instance 


def paginate_data(request, page_num, data_list):
    items_per_page, max_pages = 10, 10
    paginator = Paginator(data_list, items_per_page)
    last_page_number = paginator.num_pages

    try:
        data_list = paginator.page(page_num)
    except PageNotAnInteger:
        data_list = paginator.page(1)
    except EmptyPage:
        data_list = paginator.page(paginator.num_pages)

    current_page = data_list.number
    start_page = max(current_page - int(max_pages / 2), 1)
    end_page = start_page + max_pages

    if end_page > last_page_number:
        end_page = last_page_number + 1
        start_page = max(end_page - max_pages, 1)

    paginator_list = range(start_page, end_page)

    return data_list, paginator_list, last_page_number


@admin_required
def backend_dashboard(request):
    return render(request, 'home/home.html')


def backend_login(request):
    if request.user.is_authenticated:
        return redirect('backend:dashboard')

    form = CustomUserLoginForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user_ip = request.META.get('HTTP_X_FORWARDED_FOR') or request.META.get('REMOTE_ADDR')

        user = User.objects.filter(username=username).first()

        if user and (user.is_superuser or hasattr(user, 'admin')):
            authenticated_user = authenticate(request, username=username, password=password)

            if authenticated_user is not None:
                if user.is_superuser and not hasattr(user, 'admin'):
                    AdminUser.objects.create(user=user)

                login(request, authenticated_user)
                LoginLog.objects.create(user_id=user.id, username=username, login_ip=user_ip, login_status=True)

                next_url = request.GET.get('next', reverse('backend:backend_dashboard'))
                return redirect(next_url)

        LoginLog.objects.create(username=username, login_ip=user_ip, login_status=False)
        messages.error(request, "Invalid username or password.")
    context = {
        'form': form
    }
    return render(request, 'backend_login.html', context)


@login_required
def backend_logout(request):
    LoginLog.objects.create(
        user_id=request.user.id,
        username=request.user.username,
        login_ip=request.META.get('HTTP_X_FORWARDED_FOR') or request.META.get('REMOTE_ADDR'),
        login_status=False
    )
    logout(request)
    return redirect('backend:backend_login')


# Management Start
@method_decorator(admin_required, name='dispatch')
class UserListView(ListView):
    model = AdminUser
    template_name = 'user/list.html'
    context_object_name = 'user_list'
    ordering = ['created_at']
    paginate_by = 10

    def dispatch(self, request, *args, **kwargs):
        if not checkUserPermission(request, "can_add", "/backend/user/"):
            return render(request, "403.html")
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset().select_related('user')
        username = self.request.GET.get('username', '')
        is_active = self.request.GET.get('is_active', '')

        if username:
            queryset = queryset.filter(user__username__icontains=username)
        if is_active:
            queryset = queryset.filter(user__is_active=is_active)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.GET.get('username', '')
        context['is_active'] = self.request.GET.get('is_active', '')

        get_params = self.request.GET.copy()
        if 'page' in get_params:
            get_params.pop('page')
        context['query_params'] = get_params.urlencode()

        context['filter_user'] = AdminUser.objects.all()

        return context


@admin_required
def user_add(request):
    if not checkUserPermission(request, "can_add", "/backend/user/"):
        return render(request, "403.html")

    if request.method == 'POST':
        form = UserCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'New user has been added successfully!')
            return redirect('backend:user_list')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        form = UserCreateForm()

    return render(request, 'user/add.html', {'form': form})


@admin_required
def user_update(request, data_id):
    if not checkUserPermission(request, "can_update", "/backend/user/"):
        return render(request, "403.html")

    # management = Area.objects.filter(unique_id=data_id).first()

    # if request.method == 'POST':
    #     select_country = request.POST.get('select_country')
    #     select_district = request.POST.get('select_district')
    #     select_sub_district = request.POST.get('select_sub_district')
    #     management_name = request.POST.get('management_name')

    #     if not select_country:
    #         messages.error(request, 'Please select country')
    #         return redirect('admin_app:management_update')

    #     country = Country.objects.filter(unique_id=select_country).first()
    #     if not country:
    #         messages.error(request, 'Country not found')
    #         return redirect('admin_app:management_update')

    #     if not select_district:
    #         messages.error(request, 'Please select district')
    #         return redirect('admin_app:management_update')

    #     district = District.objects.filter(unique_id=select_district, country=country).first()
    #     if not district:
    #         messages.error(request, 'District not found')
    #         return redirect('admin_app:management_update')

    #     if not select_sub_district:
    #         messages.error(request, 'Please select sub district')
    #         return redirect('admin_app:management_update')

    #     sub_district = SubDistrict.objects.filter(unique_id=select_sub_district, district=district).first()
    #     if not sub_district:
    #         messages.error(request, 'Sub district not found')
    #         return redirect('admin_app:management_update')

    #     if not management_name:
    #         messages.error(request, 'Please enter district name')
    #         return redirect('admin_app:management_update')

    #     if not management_name:
    #         messages.error(request, 'Please enter management name')
    #         return redirect('admin_app:management_update')

    #     if len(management_name) < 3:
    #         messages.warning(request, 'Area name must be at least 3 characters')
    #         return redirect('admin_app:management_update')

    #     if Area.objects.filter(name=management_name, sub_district=sub_district).exclude(id=management.id).exists():
    #         messages.warning(request, 'Area already exists')
    #         return redirect('admin_app:management_update')
    #     else:
    #         management.name = management_name
    #         management.sub_district_id = sub_district.id
    #         management.updated_by = request.user
    #         management.save()

    #         messages.success(request, 'Area added successfully')
    #         return redirect('admin_app:management_list')

    context = {
        # "management": management
    }
    return render(request, 'user/management_update.html', context)


@admin_required
def reset_password(request, data_id):
    if not checkUserPermission(request, "can_update", "/backend/user/"):
        return render(request, "403.html")

    user = get_object_or_404(AdminUser, id=data_id)
    if request.method == 'POST':
        form = AdminPasswordChangeForm(user=user.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your password has been updated successfully.')
            return redirect('backend:backend_dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = AdminPasswordChangeForm(user=user.user)

    context = {
        'form': form,
        'user': user
    }

backend/templates/user/add.html
{% extends 'base.html' %}

{% block title%}Add Management User{% endblock %}

{% block content %}

<div class="container-fluid">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row justify-content-center">
            <div class="col-12">
                <div class="row align-items-center my-4">
                    <div class="col">
                        <h2 class="h3 mb-0 page-title">Add Management User</h2>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary">Save Change</button>
                    </div>
                </div>

                <div class="card shadow">
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="first_name">Full Name <span class="text-danger">*</span></label>
                                <input type="text" id="first_name" name="first_name" class="form-control" value="{{ form.first_name.value|default_if_none:'' }}" required>
                                {{ form.first_name.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="email">Email <span class="text-danger">*</span></label>
                                <input type="email" class="form-control" id="email" name="email" value="{{ form.email.value|default_if_none:'' }}" required>
                                {{ form.email.errors }}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="phone">Mobile No <span class="text-danger">*</span></label>
                                <input type="phone" class="form-control" id="phone" name="phone" value="{{ form.phone.value|default_if_none:'' }}" required>
                                {{ form.phone.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="gender">Gender <span class="text-danger">*</span></label>
                                <select id="gender" class="form-control" name="gender" required>
                                    <option value="male" {% if form.gender.value == 'male' %}selected{% endif %}>Male</option>
                                    <option value="female" {% if form.gender.value == 'female' %}selected{% endif %}>Female</option>
                                    <option value="other" {% if form.gender.value == 'other' %}selected{% endif %}>Other</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="profile_photo">Profile Photo</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="profile_photo" name="profile_photo" accept="image/*">
                                    <label class="custom-file-label" for="profile_photo">Choose file</label>
                                </div>
                            </div>



                            {% comment %} <div class="mt-3">
                                <label for="profile_photo" class="btn btn-secondary btn-sm">Update Photo</label>
                                <input type="file" id="profile_photo" name="profile_photo" class="d-none">
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

backend/templates/user/list.html
{% extends 'base.html' %}

{% block title%}User{% endblock %}

{% block content %}
<section class="customer-list-section">
    <div class="content">
        <div class="title-box">
            <div class="page-title">
                <h3>User List</h3>
            </div>
            <div class="breadcrumbs">
                <ul class="breadcrumbs-list">
                    <li>
                        <a href="/backend/"><span><img src="/static/images/icons/Home.svg" alt="more" /></span>Home</a>
                    </li>
                    <li><a href="#"> User List </a></li>
                </ul>
            </div>
            <div class="top-button">
                <div class="button-box">
                    <a class="button primary-button" href="{% url 'backend:user_add' %}"><span><img src="/static/images/icons/add.svg" alt="more" /></span> Add New User</a>
                </div>
            </div>
        </div>

        <div class="filter-box">
            <form method="get" class="row mb-3">
                <div class="filter-inner">
                    <div class="filter-input-field">
                        <label for="username">Full Name</label>
                        <select id="username" class="add_select2" name="username" class="form-control">
                            <option value=""></option>
                            {% for fuser in filter_user %}
                                <option value="{{ fuser.user.username }}" {% if request.GET.username and fuser.user.username == request.GET.username %} selected {% endif %}>{{ fuser.get_name }} ({{ fuser.user.username }})</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="filter-input-field">
                        <label for="is_active">Status</label>
                        <select id="is_active" class="add_select2" name="is_active" class="form-control">
                            <option value="" selected></option> 
                            <option value="1" {% if request.GET.is_active == '1' %} selected {% endif %}>Active</option> 
                            <option value="0" {% if request.GET.is_active == '0' %} selected {% endif %}>Inactive</option> 
                        </select>
                    </div>
                    <div class="filter-input-field">
                        <label for="filter-button"></label>
                        <div class="filter-button" id="filter-button">
                            <button type="submit" class="button blue-button">Filter</button>
                            <a class="button primary-button" href="{% url 'backend:user_list' %}">Clear</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="listing-box group-permission-box">
            <div class="table table-border-bottom">
                <table>
                    <tr>
                        <th class="text-center">Image</th>
                        <th class="text-left">Name</th>
                        <th class="text-left">Username</th>
                        <th class="text-left">Email</th>
                        <th class="text-left">Phone</th>
                        <th class="text-center">Joined Date</th>
                        <th class="text-center">Action</th>
                    </tr>

                    {% for data in user_list %}
                        <tr>
                            <td class="text-center"><img src="{{ data.get_profile_photo_url }}" alt="..." class="avatar-img rounded-circle"></td>
                            <td class="text-left">{{ data.user.first_name|default:"" }}</td>
                            <td class="text-left">{{ data.user.username|default:"" }}</td>
                            <td class="text-left">{{ data.user.email|default:"" }}</td>
                            <td class="text-left">{{ data.phone|default:"" }}</td>
                            <td class="text-center">{{ data.user.date_joined|date:"d-M-Y" }}</td>
                            {% comment %} <td class="text-center">
                                <span class="more">
                                    <a href="#"><i class="fas fa-edit font-weight500"></i></a>
                                </span>
                            </td> {% endcomment %}
                            <td class="text-center">
                                <button class="btn btn-sm dropdown-toggle" type="button">
                                    <span class="text-muted sr-only">Action</span>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="{% url 'backend:user_permission' data.user.id %}">User Permission</a>
                                    <a class="dropdown-item" href="{% url 'backend:reset_password' data.id %}">Reset Password</a>
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                    <tr>
                        <td colspan="8" class="text-center">No Data found.</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

            <!-- pagination -->
            <div class="pagination">
                {% if is_paginated %}
                    <div class="col-md-12 text-end">
                        <nav aria-label="navigation">
                            <ul class="pagination justify-content-center">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ query_params }}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                {% endif %}

                                {% with show_left_dots=False show_right_dots=False %}
                                    {% for num in paginator.page_range %}
                                        {% if num <= 2 or num > paginator.num_pages|add:'-2' or num >= page_obj.number|add:'-1' and num <= page_obj.number|add:'1' %}
                                            {% if num == page_obj.number %}
                                                <li class="page-item active">
                                                    <a class="page-link" href="#">{{ num }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ num }}&{{ query_params }}">{{ num }}</a>
                                                </li>
                                            {% endif %}
                                        {% comment %} {% elif num == 3 and not show_left_dots %}
                                            <li class="page-item disabled"><span class="page-link">...</span></li>
                                            {% with True as show_left_dots %}
                                            {% endwith %}
                                        {% elif num == paginator.num_pages|add:'-2' and not show_right_dots %}
                                            <li class="page-item disabled"><span class="page-link">...</span></li>
                                            {% with True as show_right_dots %}
                                            {% endwith %} {% endcomment %}
                                        {% endif %}
                                    {% endfor %}
                                {% endwith %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ query_params }}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>	

<script>
    $(".add_select2").select2();
</script>

{% endblock %}